[package]
name = "meru-interface"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.58"
bevy_input = "0.7"
egui = "0.18"
serde = "1.0.137"
