[package]
name = "meru-interface"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.58"
bevy = "0.7.0"
bevy_egui = "0.14.0"
serde = "1.0.137"
