[workspace]
members = ["meru-interface"]

[package]
name = "meru"
version = "0.1.0"
edition = "2021"
authors = ["Hideyuki Tanaka <tanaka.hideyuki@gmail.com>"]
license = "MIT"

description = "Multi game console Emulator written in Rust"
repository = "https://github.com/tanakh/tgba"
readme = "README.md"
categories = ["emulators"]
keywords = ["emulators"]

[dependencies]
meru-interface = { path = "meru-interface", version = "0.1.0" }
tgbr = { git = "https://github.com/tanakh/tgbr", version = "0.2.0" }
tgba = { git = "https://github.com/tanakh/tgba", version = "0.1.0" }

anyhow = "1.0.58"
bevy = { version = "0.7", features = ["serialize"] }
bevy_easings = "0.7"
bevy_egui = "0.14"
bevy_tiled_camera = "0.3.1"
chrono = "0.4.19"
compress-tools = "0.12.2"
cpal = "0.13.5"
directories = "4.0.1"
enum-iterator = "1.1.2"
image = { version = "0.24.2", default-features = false, features = ["ico"] }
log = "0.4.17"
rfd = "0.9"
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.81"
tempfile = "3.3.0"
winit = "0.26.1"

[target.'cfg(windows)'.build-dependencies]
winres = "0.1"

[package.metadata.vcpkg]
git = "https://github.com/microsoft/vcpkg"
branch = "master"
dependencies = ["libarchive"]

[package.metadata.vcpkg.target]
x86_64-pc-windows-msvc = { triplet = "x64-windows-static-md" }
