name: Deploy web app to Pages

on:
  push:
    tags:
      - 'v*'

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Build | Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          target: wasm32-unknown-unknown
          override: true

      - name: Build | Install wasm-bindgen-cli
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: wasm-bindgen-cli

      - name: Build | Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --target=wasm32-unknown-unknown

      - name: Build | Generate page
        run: wasm-bindgen --out-dir ./web/ --target web ./target/wasm32-unknown-unknown/release/meru.wasm

      - name: Setup Pages
        uses: actions/configure-pages@v2

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: 'web'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
